# Generated by Django 4.2.28 on 2026-03-31 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
    ]
