# Generated by Django 4.2.28 on 2026-03-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20260330_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banner_colour',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
