# Generated by Django 4.2.28 on 2026-03-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_banner_colour_customuser_pronouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='banner_colour',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
