# Generated by Django 4.2.28 on 2026-04-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_banner_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('officer', 'CIO Officer'), ('user_admin', 'User Administrator')], default='student', max_length=20),
        ),
    ]
