# Generated by Django 4.2.28 on 2026-04-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('member', 'Member'), ('officer', 'CIO Officer'), ('user_admin', 'User Administrator')], default='viewer', max_length=20),
        ),
    ]
