# Generated by Django 4.2.28 on 2026-04-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cio',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='cio_about_images/'),
        ),
        migrations.AddField(
            model_name='cio',
            name='commitment_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cio',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cio',
            name='dues',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cio',
            name='time_expectations',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
