# Generated by Django 4.2.28 on 2026-04-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cios', '0003_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cio',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='cio_banners/'),
        ),
        migrations.AddField(
            model_name='cio',
            name='gradient',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
