# Generated by Django 4.2.28 on 2026-04-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cios', '0004_cio_banner_image_cio_gradient'),
    ]

    operations = [
        migrations.AddField(
            model_name='cio',
            name='banner_type',
            field=models.CharField(choices=[('default', 'Default'), ('custom', 'Custom'), ('image', 'Image')], default='default', max_length=10),
        ),
    ]
