# Generated by Django 4.2.28 on 2026-04-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cios', '0005_cio_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cio',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='cio_icons/'),
        ),
    ]
