# Generated by hand for Codex on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kind',
            field=models.CharField(
                choices=[('announcement', 'Announcement'), ('discussion', 'Discussion')],
                default='announcement',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
